version: "1.0"

services:
  frontend:
    ports:
      - "3000:3000"
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    ports:
      - "5000:5000"
    build:
      context: ./backend
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules
